### ISSUE TITLE
加入对 archive.today 等存档站点链接的收录

### ISSUE THREAD

**Issue by andylizi** [Albert-W/zhihu-dustbin#5]
如题。[archive.today](https://en.wikipedia.org/wiki/Archive.today) 中存档下来的知乎404内容十分可观，但里面也混杂了不少“正常”的专栏与回答，不方便搜寻与浏览。建议加入一个专门索引这类内容的 issue，或者也可以考虑用爬虫批量筛选出原页面已被404的内容？毕竟如果要求必须作者本人来提交的话，受众范围恐怕十分有限，但任何人都可以向 archive.today 主动发起快照请求，将页面永久保存。如果只索引指向快照的链接，应该不会涉及到版权问题。

* 备份域名：根域名除了 [.today](https://archive.today/) 外还有 [.ph](https://archive.ph/)、[.vn](https://archive.vn/)、[.is](https://archive.is/)、[.li](https://archive.li/)、[.fo](https://archive.fo/) 和 [.md](https://archive.md/) 结尾的变种。如果链接打不开，可以把其中域名部分替换成别的镜像。应该都需要梯子。
* 列出存档的所有问题与回答：[https://archive.ph/https://www.zhihu.com/*](https://archive.ph/https://www.zhihu.com/*)
* 列出存档的所有专栏文章：[https://archive.ph/zhuanlan.zhihu.com](https://archive.ph/zhuanlan.zhihu.com)
* 已被404的例子：
    * [十年前公知真的很盛行吗？胭脂帝国的回答 - 知乎](https://archive.ph/nbYwj)
    * [如何激怒一个左派？ - 知乎](https://archive.ph/uC59y)
    * [为什么沈从文、冰心等大作家在建国后没有什么佳作？李傲文的回答 - 知乎](https://archive.ph/nbYwj)

**Comment by andylizi** [comment]
顺便说一句，没有仓库权限是不能给 issue 打 tag 的，但 Github 有个 issue template 功能，可以让依据模板创建的 issue 自动带上指定的 tag，不再需要人工操作。详见：[Configuring issue templates for your repository - GitHub Docs](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

**Comment by Albert-W** [comment]
> 顺便说一句，没有仓库权限是不能给 issue 打 tag 的，但 Github 有个 issue template 功能，可以让依据模板创建的 issue 自动带上指定的 tag，不再需要人工操作。详见：[Configuring issue templates for your repository - GitHub Docs](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

这个非常有用，已经改进。

**Comment by Albert-W** [comment]
> 如题。[archive.today](https://en.wikipedia.org/wiki/Archive.today) 中存档下来的知乎404内容十分可观，但里面也混杂了不少“正常”的专栏与回答，不方便搜寻与浏览。建议加入一个专门索引这类内容的 issue，或者也可以考虑用爬虫批量筛选出原页面已被404的内容？毕竟如果要求必须作者本人来提交的话，受众范围恐怕十分有限，但任何人都可以向 archive.today 主动发起快照请求，将页面永久保存。如果只索引指向快照的链接，应该不会涉及到版权问题。
> 
> * 备份域名：根域名除了 [.today](https://archive.today/) 外还有 [.ph](https://archive.ph/)、[.vn](https://archive.vn/)、[.is](https://archive.is/)、[.li](https://archive.li/)、[.fo](https://archive.fo/) 和 [.md](https://archive.md/) 结尾的变种。如果链接打不开，可以把其中域名部分替换成别的镜像。应该都需要梯子。
> * 列出存档的所有问题与回答：https://archive.ph/https://www.zhihu.com/*
> * 列出存档的所有专栏文章：https://archive.ph/zhuanlan.zhihu.com
> * 已被404的例子：
>   
>   * [十年前公知真的很盛行吗？胭脂帝国的回答 - 知乎](https://archive.ph/nbYwj)
>   * [如何激怒一个左派？ - 知乎](https://archive.ph/uC59y)
>   * [为什么沈从文、冰心等大作家在建国后没有什么佳作？李傲文的回答 - 知乎](https://archive.ph/nbYwj)

一般人在文章被删之后，来不及保存快照了。 
我可看推荐大家去这里查看内容，但不会为他建立索引。
